MYGLJKSQBC=function(){
	OOYMLWKRVM();
	
};

YIHQSYEOTY=function(){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,0,null));
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	EABXADHEVT('WWYKUMYJBJ');

	var NOFEDXHMLS=WIEVLYANFM("U",0);
	var GHTWROCHVV=FIGQBSJQGA("U",0);
	
	//GSXGWASLIY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	PQUFIBKJJH = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		PQUFIBKJJH.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		PQUFIBKJJH.onComplete.add( function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); ECVUHVMSJT(); } );
		PQUFIBKJJH.start();
		FXGSEGRXKC.pop();
		

};

ECVUHVMSJT=function(){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,1,null));
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	EABXADHEVT('WWYKUMYJBJ');
	
	var NOFEDXHMLS=WIEVLYANFM("U",1);
	var GHTWROCHVV=FIGQBSJQGA("U",1);
	
	//GSXGWASLIY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	LJRRHVSVKD = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		LJRRHVSVKD.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		LJRRHVSVKD.onComplete.add(function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); QVIAXMJHOT(); } );
		LJRRHVSVKD.start();
		FXGSEGRXKC.pop();
};

QVIAXMJHOT=function(){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,2,null));
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	EABXADHEVT('WWYKUMYJBJ');
	
	var NOFEDXHMLS=WIEVLYANFM("U",2);
	var GHTWROCHVV=FIGQBSJQGA("U",2);
	
	//GSXGWASLIY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	LCYAHFBDTT = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		LCYAHFBDTT.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);		
		LCYAHFBDTT.onComplete.add(function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); PKTNQCKKGY(); } );
		LCYAHFBDTT.start();
		FXGSEGRXKC.pop();
};



PKTNQCKKGY=function(){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,0,null));
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	EABXADHEVT('WWYKUMYJBJ');
	
	var NOFEDXHMLS=WIEVLYANFM("L",0);
	var GHTWROCHVV=FIGQBSJQGA("L",0);
	
	//GSXGWASLIY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NEPGDYQDEI = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		NEPGDYQDEI.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		NEPGDYQDEI.onComplete.add( function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); QEALPJSXNP(); } );
		NEPGDYQDEI.start();
		FXGSEGRXKC.pop();
		
};


QEALPJSXNP=function(){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,1,null));
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	EABXADHEVT('WWYKUMYJBJ');
	
	var NOFEDXHMLS=WIEVLYANFM("L",1);
	var GHTWROCHVV=FIGQBSJQGA("L",1);
	
	//GSXGWASLIY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	HHBPAROITT = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		HHBPAROITT.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		HHBPAROITT.onComplete.add(function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); CQCUXTHWQM(); } );
		HHBPAROITT.start();
		FXGSEGRXKC.pop();
		
};


CQCUXTHWQM=function(){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,2,null));
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	EABXADHEVT('WWYKUMYJBJ');
	
	
	var NOFEDXHMLS=WIEVLYANFM("L",2);
	var GHTWROCHVV=FIGQBSJQGA("L",2);
	
	//GSXGWASLIY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	EWXBTDLSHW = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		EWXBTDLSHW.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		EWXBTDLSHW.onComplete.add( function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); MJEINBTAOX(); } );
		EWXBTDLSHW.start();
		FXGSEGRXKC.pop();
		
		
};



OOYMLWKRVM=function(){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,0,null));
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	EABXADHEVT('WWYKUMYJBJ');
	
	var NOFEDXHMLS=WIEVLYANFM("D",0);
	var GHTWROCHVV=FIGQBSJQGA("D",0);
	
	//GSXGWASLIY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	BDEFDQUJJE = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		BDEFDQUJJE.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		
		BDEFDQUJJE.onComplete.add(function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); HKFXDKKDUH(); } );
	
	//BDEFDQUJJE=YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale);
		YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);

		BDEFDQUJJE.start();
		
		
		
		FXGSEGRXKC.pop();
		

};

HKFXDKKDUH=function(){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,1,null));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",1);
	var GHTWROCHVV=FIGQBSJQGA("D",1);
	
	//GSXGWASLIY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	CKOUBGTDUF = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		CKOUBGTDUF.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		CKOUBGTDUF.onComplete.add(function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); HCBSNXQFAP(); } );
		CKOUBGTDUF.start();
		
		YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		
		FXGSEGRXKC.pop();
};

HCBSNXQFAP=function(){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,2,null));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",2);
	var GHTWROCHVV=FIGQBSJQGA("D",2);
	
	//GSXGWASLIY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	JLFYUAKDIJ = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		JLFYUAKDIJ.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);		
		JLFYUAKDIJ.onComplete.add(function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); JTSKISTHON(); } );
		YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		
		JLFYUAKDIJ.start();
		FXGSEGRXKC.pop();
};


JTSKISTHON=function(){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,0,null));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",0);
	var GHTWROCHVV=FIGQBSJQGA("R",0);
	
	//GSXGWASLIY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add(function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); QSTNPSSTIR(); } );
		s.start();
		FXGSEGRXKC.pop();
};


QSTNPSSTIR=function(){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,1,null));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",1);
	var GHTWROCHVV=FIGQBSJQGA("R",1);
	
	//GSXGWASLIY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add(function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); XLOSOVGUJS(); } );
		s.start();
		FXGSEGRXKC.pop();
};


XLOSOVGUJS=function(){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,2,null));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",2);
	var GHTWROCHVV=FIGQBSJQGA("R",2);
	
	//GSXGWASLIY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add(function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); YIHQSYEOTY(); } );
		s.start();
		FXGSEGRXKC.pop();
};

// SEGUNDA PASADA

MMCHJUNMOH=function(){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,3,null));
	EABXADHEVT('WWYKUMYJBJ');
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("U",3);
	var GHTWROCHVV=FIGQBSJQGA("U",3);
	
	//GSXGWASLIY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add(function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); VVUFPAXPEH(); } );
		s.start();
		FXGSEGRXKC.pop();
		

};

VVUFPAXPEH=function(){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,4,null));
	EABXADHEVT('WWYKUMYJBJ');
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("U",4);
	var GHTWROCHVV=FIGQBSJQGA("U",4);
	
	//GSXGWASLIY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add(function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); JQGLCLODAD(); } );
		s.start();
		FXGSEGRXKC.pop();
};

JQGLCLODAD=function(){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,5,null));
	EABXADHEVT('WWYKUMYJBJ');
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("U",5);
	var GHTWROCHVV=FIGQBSJQGA("U",5);
	
	//GSXGWASLIY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);		
		s.onComplete.add(function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); GEEPCOBPDV(); } );
		s.start();
		FXGSEGRXKC.pop();
};



GEEPCOBPDV=function(){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,3,null));
	EABXADHEVT('WWYKUMYJBJ');
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("L",3);
	var GHTWROCHVV=FIGQBSJQGA("L",3);
	
	//GSXGWASLIY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add(function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); HUVEOQXRGJ(); } );
		s.start();
		FXGSEGRXKC.pop();
};


HUVEOQXRGJ=function(){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,4,null));
	EABXADHEVT('WWYKUMYJBJ');
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("L",4);
	var GHTWROCHVV=FIGQBSJQGA("L",4);
	
	//GSXGWASLIY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add(function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); SSKBQFUCWK(); } );
		s.start();
		FXGSEGRXKC.pop();
};


SSKBQFUCWK=function(){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,5,null));
	EABXADHEVT('WWYKUMYJBJ');
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("L",5);
	var GHTWROCHVV=FIGQBSJQGA("L",5);
	
	//GSXGWASLIY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		//s.onComplete.add(MJEINBTAOX,this)
		s.onComplete.add(function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); QYYXUWQADX(); } );
		s.start();
		FXGSEGRXKC.pop();
		// JQSOOBSDDS();
};



MJEINBTAOX=function(){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,3,null));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",3);
	var GHTWROCHVV=FIGQBSJQGA("D",3);
	
	//GSXGWASLIY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add(function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); YTQGBXJKGR(); } );
		s.start();
		YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
		

};

YTQGBXJKGR=function(){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,4,null));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",4);
	var GHTWROCHVV=FIGQBSJQGA("D",4);
	
	//GSXGWASLIY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add(function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); AVOTBVVLEX(); } );
		s.start();
		YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
};

AVOTBVVLEX=function(){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,5,null));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	var NOFEDXHMLS=WIEVLYANFM("D",5);
	var GHTWROCHVV=FIGQBSJQGA("D",5);
	
	//GSXGWASLIY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);		
		s.onComplete.add(function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); CXXGPYOJUA(); } );
		s.start();
		YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
};


CXXGPYOJUA=function(){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,3,null));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",3);
	var GHTWROCHVV=FIGQBSJQGA("R",3);
	
	//GSXGWASLIY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add(function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); UNHAIXXITK(); } );
		s.start();
		FXGSEGRXKC.pop();
};


UNHAIXXITK=function(){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,4,null));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",4);
	var GHTWROCHVV=FIGQBSJQGA("R",4);
	
	//GSXGWASLIY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add(function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); HTBNQFIKRW(); } );
		s.start();
		FXGSEGRXKC.pop();
};


HTBNQFIKRW=function(){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,5,null));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",5);
	var GHTWROCHVV=FIGQBSJQGA("R",5);
	
	//GSXGWASLIY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add(function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); MMCHJUNMOH(); } );
		s.start();
		FXGSEGRXKC.pop();
};

