EUNGWSACEK=function(){
	XALJNKGKXN();
};

XLGSARNUBL=function(){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,0,null));
	EABXADHEVT('WWYKUMYJBJ');
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("U",0);
	var GHTWROCHVV=FIGQBSJQGA("U",0);
	

	PQUFIBKJJH = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		PQUFIBKJJH.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV
		}, IRXOKNWTLV, BSXWFYLCEW);
		PQUFIBKJJH.onComplete.add( function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); NBOXKNLUUR(); } );
		PQUFIBKJJH.start();
		FXGSEGRXKC.pop();
	
	

};

NBOXKNLUUR=function(){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,1,null));
	EABXADHEVT('WWYKUMYJBJ');
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("U",1);
	var GHTWROCHVV=FIGQBSJQGA("U",1);
	
	LJRRHVSVKD = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		LJRRHVSVKD.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV
		}, IRXOKNWTLV, BSXWFYLCEW);
		LJRRHVSVKD.onComplete.add( function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); GEHYGJVLCX(); } );
		LJRRHVSVKD.start();
		FXGSEGRXKC.pop();
};

GEHYGJVLCX=function(){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,2,null));
	EABXADHEVT('WWYKUMYJBJ');
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("U",2);
	var GHTWROCHVV=FIGQBSJQGA("U",2);
	
	LCYAHFBDTT = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		LCYAHFBDTT.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV
		}, IRXOKNWTLV, BSXWFYLCEW);		
		LCYAHFBDTT.onComplete.add( function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); GMXSPHUAWP(); } );
		LCYAHFBDTT.start();
		FXGSEGRXKC.pop();
};



GMXSPHUAWP=function(){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,0,null));
	EABXADHEVT('WWYKUMYJBJ');
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("L",0);
	var GHTWROCHVV=FIGQBSJQGA("L",0);
	
	NEPGDYQDEI = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		NEPGDYQDEI.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		NEPGDYQDEI.onComplete.add( function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); YKKCWUNYPN(); } );
		NEPGDYQDEI.start();
		FXGSEGRXKC.pop();
};


YKKCWUNYPN=function(){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,1,null));
	EABXADHEVT('WWYKUMYJBJ');
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("L",1);
	var GHTWROCHVV=FIGQBSJQGA("L",1);
	
	HHBPAROITT = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		HHBPAROITT.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		HHBPAROITT.onComplete.add( function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); RVEPHBTXKX(); } );
		HHBPAROITT.start();
		FXGSEGRXKC.pop();
};


RVEPHBTXKX=function(){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,2,null));
	EABXADHEVT('WWYKUMYJBJ');
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("L",2);
	var GHTWROCHVV=FIGQBSJQGA("L",2);
	
	BDEFDQUJJE = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		BDEFDQUJJE.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		BDEFDQUJJE.onComplete.add( function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); PHGHYUOWTN(); } );
		BDEFDQUJJE.start();
		FXGSEGRXKC.pop();
};



PHGHYUOWTN=function(){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,0,null));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",0);
	var GHTWROCHVV=FIGQBSJQGA("D",0);
	
	CKOUBGTDUF = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		CKOUBGTDUF.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		CKOUBGTDUF.onComplete.add( function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); KDVKJEBYUU(); } );
		CKOUBGTDUF.start();
		YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
		

};

KDVKJEBYUU=function(){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,1,null));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",1);
	var GHTWROCHVV=FIGQBSJQGA("D",1);
	
	EWXBTDLSHW = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		EWXBTDLSHW.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		EWXBTDLSHW.onComplete.add( function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); JMMNLMSMJE(); } );
		//FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.inputEnabled = true;
		//FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.input.enableDrag(false,true);
		EWXBTDLSHW.start();
		YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
};

JMMNLMSMJE=function(){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,2,null));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",2);
	var GHTWROCHVV=FIGQBSJQGA("D",2);
	
	JLFYUAKDIJ = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		JLFYUAKDIJ.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);		
		JLFYUAKDIJ.onComplete.add( function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); YVIUGJDUUO(); } );
		//FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.inputEnabled = true;
		//FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.input.enableDrag(false,true);
		JLFYUAKDIJ.start();
		YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
};


XALJNKGKXN=function(){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,0,null));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",0);
	var GHTWROCHVV=FIGQBSJQGA("R",0);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add( function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); ELJAQLYAYE(); } );
		s.start();
		FXGSEGRXKC.pop();
};


ELJAQLYAYE=function(){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,1,null));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",1);
	var GHTWROCHVV=FIGQBSJQGA("R",1);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add( function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); OXGRTXEORL(); } );
		s.start();
		FXGSEGRXKC.pop();
};


OXGRTXEORL=function(){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,2,null));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",2);
	var GHTWROCHVV=FIGQBSJQGA("R",2);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add( function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); XLGSARNUBL(); } );
		s.start();
		FXGSEGRXKC.pop();
};

// SEGUNDA PASADA

UTVYHFEAFY=function(){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,3,null));
	EABXADHEVT('WWYKUMYJBJ');
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("U",3);
	var GHTWROCHVV=FIGQBSJQGA("U",3);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add( function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); QFIXRSTKNY(); } );
		s.start();
		FXGSEGRXKC.pop();
		

};

QFIXRSTKNY=function(){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,4,null));
	EABXADHEVT('WWYKUMYJBJ');
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("U",4);
	var GHTWROCHVV=FIGQBSJQGA("U",4);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add( function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); RSBORYATHB(); } );
		s.start();
		FXGSEGRXKC.pop();
};

RSBORYATHB=function(){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,5,null));
	EABXADHEVT('WWYKUMYJBJ');
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("U",5);
	var GHTWROCHVV=FIGQBSJQGA("U",5);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);		
		s.onComplete.add( function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); GFVUTLXCKB(); } );
		s.start();
		FXGSEGRXKC.pop();
};



GFVUTLXCKB=function(){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,3,null));
	EABXADHEVT('WWYKUMYJBJ');
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("L",3);
	var GHTWROCHVV=FIGQBSJQGA("L",3);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add( function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); RVVELTRXSO(); } );
		s.start();
		FXGSEGRXKC.pop();
};


RVVELTRXSO=function(){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,4,null));
	EABXADHEVT('WWYKUMYJBJ');
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("L",4);
	var GHTWROCHVV=FIGQBSJQGA("L",4);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add( function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); FPPBRATYNN(); } );
		s.start();
		FXGSEGRXKC.pop();
};


FPPBRATYNN=function(){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,5,null));
	EABXADHEVT('WWYKUMYJBJ');
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("L",5);
	var GHTWROCHVV=FIGQBSJQGA("L",5);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add( function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); XSMVMFMTPQ(); } );
		s.start();
		FXGSEGRXKC.pop();
};



XSMVMFMTPQ=function(){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,3,null));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",3);
	var GHTWROCHVV=FIGQBSJQGA("D",3);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add( function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); IFEOSLRTIQ(); } );
		//FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.inputEnabled = true;
		//FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.input.enableDrag(false,true);
		s.start();
		YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
		

};

IFEOSLRTIQ=function(){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,4,null));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",4);
	var GHTWROCHVV=FIGQBSJQGA("D",4);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add( function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); JWGGTDJAIE(); } );
		//FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.inputEnabled = true;
		//FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.input.enableDrag(false,true);
		s.start();
		YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
};

JWGGTDJAIE=function(){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,5,null));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",5);
	var GHTWROCHVV=FIGQBSJQGA("D",5);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);		
		//s.onComplete.add( function(){ YVIUGJDUUO(); } );
		//FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.inputEnabled = true;
		//FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.input.enableDrag(false,true);
		s.onComplete.add( function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); QYYXUWQADX(); } );;
		s.start();
		YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
		//JQSOOBSDDS();
};


YVIUGJDUUO=function(){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,3,null));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",3);
	var GHTWROCHVV=FIGQBSJQGA("R",3);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add( function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); NESJSTWXWP(); } );
		s.start();
		FXGSEGRXKC.pop();
};


NESJSTWXWP=function(){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,4,null));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",4);
	var GHTWROCHVV=FIGQBSJQGA("R",4);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add( function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); IABLTISPHU(); } );
		s.start();
		FXGSEGRXKC.pop();
};


IABLTISPHU=function(){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,5,null));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",5);
	var GHTWROCHVV=FIGQBSJQGA("R",5);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add( function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); UTVYHFEAFY(); } );
		s.start();
		FXGSEGRXKC.pop();
};

