'use strict';
function MLSPYKFFCM(TXLWIIINGQ){
	Renderizar(true);
	console.log("desde arriba")
	DLFGCWILYV(TXLWIIINGQ);
};

function DLFGCWILYV(TXLWIIINGQ){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,0,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	EABXADHEVT('WWYKUMYJBJ');
	
	if (EVAILWGGKX==true)
	{
		//ATTUXTNNKX.revive();
		ATTUXTNNKX.revive();
		XQDPVWOUII.revive();
		EABXADHEVT('CLVBGPCTEJ');		
	}
	else
	{
		EABXADHEVT('JCIRYRCUJJ');		
	}
	
	var NOFEDXHMLS=WIEVLYANFM("U",0);
	var GHTWROCHVV=FIGQBSJQGA("U",0);;
	

	//PQUFIBKJJH = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV
		,angle:FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 0}, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce(function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); POVOKFEASV(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
		

};

function POVOKFEASV(TXLWIIINGQ){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,1,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	EABXADHEVT('WWYKUMYJBJ');
	
	var NOFEDXHMLS=WIEVLYANFM("U",1);
	var GHTWROCHVV=FIGQBSJQGA("U",1);
	
	//LJRRHVSVKD = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce(function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); LBEWCUDHJR(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};

function LBEWCUDHJR(TXLWIIINGQ){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,2,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	EABXADHEVT('WWYKUMYJBJ');
	
	

	
	var NOFEDXHMLS=WIEVLYANFM("U",2);
	var GHTWROCHVV=FIGQBSJQGA("U",2);
	
	//LCYAHFBDTT = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);		
		twReparto.onComplete.addOnce(function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); RJEDRPCLOP(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};



function RJEDRPCLOP(TXLWIIINGQ){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,0,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	EABXADHEVT('WWYKUMYJBJ');
	
	var NOFEDXHMLS=WIEVLYANFM("L",0);
	var GHTWROCHVV=FIGQBSJQGA("L",0);
	
	//NEPGDYQDEI = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce(function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); YDCYPGDYFA(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};


function YDCYPGDYFA(TXLWIIINGQ){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,1,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	EABXADHEVT('WWYKUMYJBJ');
	
	var NOFEDXHMLS=WIEVLYANFM("L",1);
	var GHTWROCHVV=FIGQBSJQGA("L",1);
	
	//HHBPAROITT = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce(function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); MAMKKJQORI(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};


function MAMKKJQORI(TXLWIIINGQ){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,2,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	EABXADHEVT('WWYKUMYJBJ');
	
	var NOFEDXHMLS=WIEVLYANFM("L",2);
	var GHTWROCHVV=FIGQBSJQGA("L",2);
	
	//EWXBTDLSHW = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce(function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); QVLNICRTSR(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};



function QVLNICRTSR(TXLWIIINGQ){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,0,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	EABXADHEVT('WWYKUMYJBJ');
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",0);
	var GHTWROCHVV=FIGQBSJQGA("D",0);
	
	//BDEFDQUJJE = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
	FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale.setTo(QDTCADQEEX,QDTCADQEEX)	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV
		,angle:FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 0}, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce(function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); VRBJBMPORY(TXLWIIINGQ); } );
		twReparto.start();
		//YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
		

};

function VRBJBMPORY(TXLWIIINGQ){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,1,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	EABXADHEVT('WWYKUMYJBJ');
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",1);
	var GHTWROCHVV=FIGQBSJQGA("D",1);
	
	//CKOUBGTDUF = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale.setTo(QDTCADQEEX,QDTCADQEEX)	
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce(function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); PCOPSJXCXN(TXLWIIINGQ); } );
		twReparto.start();
		//YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
};

function PCOPSJXCXN(TXLWIIINGQ){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,2,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	EABXADHEVT('WWYKUMYJBJ');
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",2);
	var GHTWROCHVV=FIGQBSJQGA("D",2);
	
	//JLFYUAKDIJ = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale.setTo(QDTCADQEEX,QDTCADQEEX)	
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);		
		twReparto.onComplete.addOnce(function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); PFCDORCSJB(TXLWIIINGQ); } );
		twReparto.start();
		//YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
};


function PFCDORCSJB(TXLWIIINGQ){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,0,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",0);
	var GHTWROCHVV=FIGQBSJQGA("R",0);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce(function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); UOQSCHDVWR(TXLWIIINGQ); } );
		twReparto.start();		
		FXGSEGRXKC.pop();
};


function UOQSCHDVWR(TXLWIIINGQ){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,1,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",1);
	var GHTWROCHVV=FIGQBSJQGA("R",1);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce(function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); KMDJSSINNU(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};


function KMDJSSINNU(TXLWIIINGQ){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,2,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",2);
	var GHTWROCHVV=FIGQBSJQGA("R",2);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce(function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); INNPTAOVKC(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};

// SEGUNDA PASADA

function INNPTAOVKC(TXLWIIINGQ){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,3,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("U",3);
	var GHTWROCHVV=FIGQBSJQGA("U",3);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV
		,angle:FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 0}, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce(function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); SCISPLQDLX(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
		

};

function SCISPLQDLX(TXLWIIINGQ){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,4,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("U",4);
	var GHTWROCHVV=FIGQBSJQGA("U",4);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce(function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); BPLHYGBROB(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};

function BPLHYGBROB(TXLWIIINGQ){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,5,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("U",5);
	var GHTWROCHVV=FIGQBSJQGA("U",5);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);		
		twReparto.onComplete.addOnce(function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); KXXRIUGTME(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};



function KXXRIUGTME(TXLWIIINGQ){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,3,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("L",3);
	var GHTWROCHVV=FIGQBSJQGA("L",3);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce(function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); BPQFXEMXIH(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};


function BPQFXEMXIH(TXLWIIINGQ){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,4,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("L",4);
	var GHTWROCHVV=FIGQBSJQGA("L",4);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce(function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); DWXAYGVQVP(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};


function DWXAYGVQVP(TXLWIIINGQ){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,5,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("L",5);
	var GHTWROCHVV=FIGQBSJQGA("L",5);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce(function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); BGMJYNCPKM(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};



function BGMJYNCPKM(TXLWIIINGQ){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,3,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",3);
	var GHTWROCHVV=FIGQBSJQGA("D",3);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale.setTo(QDTCADQEEX,QDTCADQEEX)		
	
	twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV
		,angle:FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 0}, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce(function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); FOWHDIYTFS(TXLWIIINGQ); } );
		twReparto.start();
		//YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
		

};

function FOWHDIYTFS(TXLWIIINGQ){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,4,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",4);
	var GHTWROCHVV=FIGQBSJQGA("D",4);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale.setTo(QDTCADQEEX,QDTCADQEEX)	
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce(function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); HYPIMWLKLK(TXLWIIINGQ); } );
		twReparto.start();
		//YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
};

function HYPIMWLKLK(TXLWIIINGQ){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,5,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",5);
	var GHTWROCHVV=FIGQBSJQGA("D",5);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale.setTo(QDTCADQEEX,QDTCADQEEX)			
	
	twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);		
		twReparto.onComplete.addOnce(function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); WIPICQXWKF(TXLWIIINGQ); } );
		twReparto.start();
		//YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
};


function WIPICQXWKF(TXLWIIINGQ){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,3,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",3);
	var GHTWROCHVV=FIGQBSJQGA("R",3);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce(function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); GVQTPTGCOW(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};


function GVQTPTGCOW(TXLWIIINGQ){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,4,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",4);
	var GHTWROCHVV=FIGQBSJQGA("R",4);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce(function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); IYETNOTVNU(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};


function IYETNOTVNU(TXLWIIINGQ){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,5,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",5);
	var GHTWROCHVV=FIGQBSJQGA("R",5);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce(function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); QYYXUWQADX(TXLWIIINGQ); } );		
		twReparto.start();
		FXGSEGRXKC.pop();
		// JQSOOBSDDS();
};

