RPMTCXIXGA=function(TXLWIIINGQ){
	PPRNUIJOLC(TXLWIIINGQ);
};


DWVCJLTLFT=function(TXLWIIINGQ){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,0,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("U",0);
	var GHTWROCHVV=FIGQBSJQGA("U",0);

	PQUFIBKJJH = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		PQUFIBKJJH.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		PQUFIBKJJH.onComplete.add(function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); GITYOTEJCB(TXLWIIINGQ); } );
		PQUFIBKJJH.start();
		FXGSEGRXKC.pop();
		

};



GITYOTEJCB=function(TXLWIIINGQ){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,1,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("U",1);
	var GHTWROCHVV=FIGQBSJQGA("U",1);
	
	LJRRHVSVKD = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		LJRRHVSVKD.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		LJRRHVSVKD.onComplete.add(function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); XAYOFVQQCG(TXLWIIINGQ); } );
		LJRRHVSVKD.start();
		FXGSEGRXKC.pop();
};




XAYOFVQQCG=function(TXLWIIINGQ){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,2,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	

	
	
	var NOFEDXHMLS=WIEVLYANFM("U",2);
	var GHTWROCHVV=FIGQBSJQGA("U",2);
	
	LCYAHFBDTT = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		LCYAHFBDTT.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);		
		LCYAHFBDTT.onComplete.add(function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); INQEMJOSCP(TXLWIIINGQ); } );
		LCYAHFBDTT.start();
		FXGSEGRXKC.pop();
};





PPRNUIJOLC=function(TXLWIIINGQ){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,0,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	if (EVAILWGGKX==true)
	{
		//ATTUXTNNKX.revive();
		ATTUXTNNKX.revive();
		XQDPVWOUII.revive();
		EABXADHEVT('CLVBGPCTEJ');		
	}
	else
	{
		EABXADHEVT('JCIRYRCUJJ');		
	}
	
	
	var NOFEDXHMLS=WIEVLYANFM("L",0);
	var GHTWROCHVV=FIGQBSJQGA("L",0);
	
	NEPGDYQDEI = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		NEPGDYQDEI.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		NEPGDYQDEI.onComplete.add(function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); CPTBWFORBL(TXLWIIINGQ); } );
		NEPGDYQDEI.start();
		FXGSEGRXKC.pop();
};


CPTBWFORBL=function(TXLWIIINGQ){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,1,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("L",1);
	var GHTWROCHVV=FIGQBSJQGA("L",1);
	
	HHBPAROITT = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		HHBPAROITT.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		HHBPAROITT.onComplete.add(function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); KQFTDLQFIE(TXLWIIINGQ); } );
		HHBPAROITT.start();
		FXGSEGRXKC.pop();
};





KQFTDLQFIE=function(TXLWIIINGQ){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,2,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("L",2);
	var GHTWROCHVV=FIGQBSJQGA("L",2);
	
	EWXBTDLSHW = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		EWXBTDLSHW.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		EWXBTDLSHW.onComplete.add(function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD);FPNDVMQEDQ(TXLWIIINGQ); } );
		EWXBTDLSHW.start();
		FXGSEGRXKC.pop();
};





FPNDVMQEDQ=function(TXLWIIINGQ){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,0,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",0);
	var GHTWROCHVV=FIGQBSJQGA("D",0);
	
	BDEFDQUJJE = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		BDEFDQUJJE.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		BDEFDQUJJE.onComplete.add(function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD);HKEFSBMWPH(TXLWIIINGQ); } );
		BDEFDQUJJE.start();
		YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
		

};


HKEFSBMWPH=function(TXLWIIINGQ){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,1,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",1);
	var GHTWROCHVV=FIGQBSJQGA("D",1);
	
	CKOUBGTDUF = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		CKOUBGTDUF.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		CKOUBGTDUF.onComplete.add(function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); HIVFBMLVXH(TXLWIIINGQ); } );
		CKOUBGTDUF.start();
		YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
};





HIVFBMLVXH=function(TXLWIIINGQ){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,2,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",2);
	var GHTWROCHVV=FIGQBSJQGA("D",2);
	
	JLFYUAKDIJ = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		JLFYUAKDIJ.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);		
		JLFYUAKDIJ.onComplete.add(function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); VMCYVGKCHH(TXLWIIINGQ); } );
		JLFYUAKDIJ.start();
		YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
};




VMCYVGKCHH=function(TXLWIIINGQ){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,0,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",0);
	var GHTWROCHVV=FIGQBSJQGA("R",0);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add(function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); PRTNWAIQGT(TXLWIIINGQ); } );
		s.start();
		FXGSEGRXKC.pop();
};




PRTNWAIQGT=function(TXLWIIINGQ){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,1,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",1);
	var GHTWROCHVV=FIGQBSJQGA("R",1);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add(function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); VQXEHLSCJV(TXLWIIINGQ); } );
		s.start();
		FXGSEGRXKC.pop();
};



VQXEHLSCJV=function(TXLWIIINGQ){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,2,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",2);
	var GHTWROCHVV=FIGQBSJQGA("R",2);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add(function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); DWVCJLTLFT(TXLWIIINGQ); } );
		s.start();
		FXGSEGRXKC.pop();
};


// SEGUNDA PASADA

LBLWWILWGV=function(TXLWIIINGQ){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,3,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("U",3);
	var GHTWROCHVV=FIGQBSJQGA("U",3);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add(function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); SXVSSQMCNS(TXLWIIINGQ); } );
		s.start();
		FXGSEGRXKC.pop();
		

};

SXVSSQMCNS=function(TXLWIIINGQ){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,4,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("U",4);
	var GHTWROCHVV=FIGQBSJQGA("U",4);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add(function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); PRSAPRHAMB(TXLWIIINGQ); } );
		s.start();
		FXGSEGRXKC.pop();
};

PRSAPRHAMB=function(TXLWIIINGQ){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,5,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("U",5);
	var GHTWROCHVV=FIGQBSJQGA("U",5);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);		
		//s.onComplete.add(INQEMJOSCP,this)
		s.onComplete.add(function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); QYYXUWQADX(TXLWIIINGQ); } );
		s.start();
		FXGSEGRXKC.pop();
		//JQSOOBSDDS();
};



INQEMJOSCP=function(TXLWIIINGQ){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,3,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("L",3);
	var GHTWROCHVV=FIGQBSJQGA("L",3);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add(function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); DCMSDUMKVR(TXLWIIINGQ); } );
		s.start();
		FXGSEGRXKC.pop();
};


DCMSDUMKVR=function(TXLWIIINGQ){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,4,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("L",4);
	var GHTWROCHVV=FIGQBSJQGA("L",4);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add(function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); DBHUFSIMNO(TXLWIIINGQ); } );
		s.start();
		FXGSEGRXKC.pop();
};


DBHUFSIMNO=function(TXLWIIINGQ){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,5,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("L",5);
	var GHTWROCHVV=FIGQBSJQGA("L",5);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add(function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); XUJGUFVMBP(TXLWIIINGQ); } );
		s.start();
		FXGSEGRXKC.pop();
};



XUJGUFVMBP=function(TXLWIIINGQ){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,3,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",3);
	var GHTWROCHVV=FIGQBSJQGA("D",3);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add(function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); JHJQDCOTLB(TXLWIIINGQ); } );
		s.start();
		YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
		

};

JHJQDCOTLB=function(TXLWIIINGQ){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,4,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",4);
	var GHTWROCHVV=FIGQBSJQGA("D",4);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add(function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); YTTJELQLUH(TXLWIIINGQ); } );
		s.start();
		YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
};

YTTJELQLUH=function(TXLWIIINGQ){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,5,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",5);
	var GHTWROCHVV=FIGQBSJQGA("D",5);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);		
		s.onComplete.add(function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); AVBRKFCIOB(TXLWIIINGQ); } );
		s.start();
		YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
};


AVBRKFCIOB=function(TXLWIIINGQ){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,3,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",3);
	var GHTWROCHVV=FIGQBSJQGA("R",3);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add(function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); ECQUSGNMRO(TXLWIIINGQ); } );
		s.start();
		FXGSEGRXKC.pop();
};


ECQUSGNMRO=function(TXLWIIINGQ){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,4,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",4);
	var GHTWROCHVV=FIGQBSJQGA("R",4);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add(function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); RWWDLCBKMR(TXLWIIINGQ); } );
		s.start();
		FXGSEGRXKC.pop();
};


RWWDLCBKMR=function(TXLWIIINGQ){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,5,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",5);
	var GHTWROCHVV=FIGQBSJQGA("R",5);
	
	var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
		s.to( {
		x:NOFEDXHMLS,
		y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		s.onComplete.add(function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); LBLWWILWGV(TXLWIIINGQ); } );
		s.start();
		FXGSEGRXKC.pop();
};
