'use strict';
function EUNGWSACEK(TXLWIIINGQ){
		Renderizar(true);
	console.log("desde derecha")
	XALJNKGKXN(TXLWIIINGQ);
};

function XLGSARNUBL(TXLWIIINGQ){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,0,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("U",0);
	var GHTWROCHVV=FIGQBSJQGA("U",0);
	

	//PQUFIBKJJH = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV
		,angle:FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 0}, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce( function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); NBOXKNLUUR(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
	
	

};

function NBOXKNLUUR(TXLWIIINGQ){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,1,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("U",1);
	var GHTWROCHVV=FIGQBSJQGA("U",1);
	
	//LJRRHVSVKD = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV
		}, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce( function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); GEHYGJVLCX(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};

function GEHYGJVLCX(TXLWIIINGQ){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,2,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	
	

	
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("U",2);
	var GHTWROCHVV=FIGQBSJQGA("U",2);
	
	//LCYAHFBDTT = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV
		}, IRXOKNWTLV, BSXWFYLCEW);		
		twReparto.onComplete.addOnce( function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); GMXSPHUAWP(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};



function GMXSPHUAWP(TXLWIIINGQ){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,0,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("L",0);
	var GHTWROCHVV=FIGQBSJQGA("L",0);
	
	//NEPGDYQDEI = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce( function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); YKKCWUNYPN(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};


function YKKCWUNYPN(TXLWIIINGQ){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,1,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("L",1);
	var GHTWROCHVV=FIGQBSJQGA("L",1);
	
	//HHBPAROITT = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce( function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); RVEPHBTXKX(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};


function RVEPHBTXKX(TXLWIIINGQ){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,2,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("L",2);
	var GHTWROCHVV=FIGQBSJQGA("L",2);
	
	//BDEFDQUJJE = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce( function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); PHGHYUOWTN(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};



function PHGHYUOWTN(TXLWIIINGQ){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,0,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",0);
	var GHTWROCHVV=FIGQBSJQGA("D",0);
	
	//CKOUBGTDUF = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale.setTo(QDTCADQEEX,QDTCADQEEX)		
	
	twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV
		,angle:FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 0}, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce( function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); KDVKJEBYUU(TXLWIIINGQ); } );
		twReparto.start();
		//YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
		

};

function KDVKJEBYUU(TXLWIIINGQ){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,1,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",1);
	var GHTWROCHVV=FIGQBSJQGA("D",1);
	
	//EWXBTDLSHW = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale.setTo(QDTCADQEEX,QDTCADQEEX)		
	
	twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce( function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); JMMNLMSMJE(TXLWIIINGQ); } );
		//FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.inputEnabled = true;
		//FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.input.enableDrag(false,true);
		twReparto.start();
		//YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
};

function JMMNLMSMJE(TXLWIIINGQ){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,2,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",2);
	var GHTWROCHVV=FIGQBSJQGA("D",2);
	
	//JLFYUAKDIJ = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale.setTo(QDTCADQEEX,QDTCADQEEX)		
	
	twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);		
		twReparto.onComplete.addOnce( function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); YVIUGJDUUO(TXLWIIINGQ); } );
		//FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.inputEnabled = true;
		//FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.input.enableDrag(false,true);
		twReparto.start();
		//YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
};


function XALJNKGKXN(TXLWIIINGQ){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,0,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	
	if (EVAILWGGKX==true)
	{
		//ATTUXTNNKX.revive();
		ATTUXTNNKX.revive();
		XQDPVWOUII.revive();
		EABXADHEVT('CLVBGPCTEJ');		
	}
	else
	{
		EABXADHEVT('JCIRYRCUJJ');		
	}
	
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",0);
	var GHTWROCHVV=FIGQBSJQGA("R",0);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce( function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); ELJAQLYAYE(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};


function ELJAQLYAYE(TXLWIIINGQ){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,1,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",1);
	var GHTWROCHVV=FIGQBSJQGA("R",1);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce( function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); OXGRTXEORL(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};


function OXGRTXEORL(TXLWIIINGQ){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,2,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",2);
	var GHTWROCHVV=FIGQBSJQGA("R",2);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce( function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); XLGSARNUBL(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};

// SEGUNDA PASADA

function UTVYHFEAFY(TXLWIIINGQ){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,3,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("U",3);
	var GHTWROCHVV=FIGQBSJQGA("U",3);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV
		,angle:FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 0}, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce( function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); QFIXRSTKNY(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
		

};

function QFIXRSTKNY(TXLWIIINGQ){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,4,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("U",4);
	var GHTWROCHVV=FIGQBSJQGA("U",4);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce( function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); RSBORYATHB(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};

function RSBORYATHB(TXLWIIINGQ){
	TWJONOKGHC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,5,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//PBHYCULPGK.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("U",5);
	var GHTWROCHVV=FIGQBSJQGA("U",5);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);		
		twReparto.onComplete.addOnce( function(){ PBHYCULPGK.add(TWJONOKGHC[TWJONOKGHC.length-1].TNFAGGMKXD); GFVUTLXCKB(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};



function GFVUTLXCKB(TXLWIIINGQ){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,3,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("L",3);
	var GHTWROCHVV=FIGQBSJQGA("L",3);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce( function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); RVVELTRXSO(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};


function RVVELTRXSO(TXLWIIINGQ){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,4,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("L",4);
	var GHTWROCHVV=FIGQBSJQGA("L",4);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce( function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); FPPBRATYNN(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};


function FPPBRATYNN(TXLWIIINGQ){
	KNVKGHHTYC.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,5,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//SYXHGDSJDY.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("L",5);
	var GHTWROCHVV=FIGQBSJQGA("L",5);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 90
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce( function(){ SYXHGDSJDY.add(KNVKGHHTYC[KNVKGHHTYC.length-1].TNFAGGMKXD); XSMVMFMTPQ(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};



function XSMVMFMTPQ(TXLWIIINGQ){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,3,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",3);
	var GHTWROCHVV=FIGQBSJQGA("D",3);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale.setTo(QDTCADQEEX,QDTCADQEEX)			
	
	twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV
		,angle:FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 0}, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce( function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); IFEOSLRTIQ(TXLWIIINGQ); } );
		//FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.inputEnabled = true;
		//FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.input.enableDrag(false,true);
		twReparto.start();
		//YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
		

};

function IFEOSLRTIQ(TXLWIIINGQ){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,4,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",4);
	var GHTWROCHVV=FIGQBSJQGA("D",4);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale.setTo(QDTCADQEEX,QDTCADQEEX)		
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce( function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); JWGGTDJAIE(TXLWIIINGQ); } );
		//FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.inputEnabled = true;
		//FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.input.enableDrag(false,true);
		twReparto.start();
		//YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
};

function JWGGTDJAIE(TXLWIIINGQ){
	AGKVNAGGLB.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,5,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//RXKKPILDQT.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	NAYBJTKIKA(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("D",5);
	var GHTWROCHVV=FIGQBSJQGA("D",5);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale.setTo(QDTCADQEEX,QDTCADQEEX)		
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV}, IRXOKNWTLV, BSXWFYLCEW);		
		//twReparto.onComplete.addOnce( function(){ YVIUGJDUUO(); } );
		//FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.inputEnabled = true;
		//FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.input.enableDrag(false,true);
		twReparto.onComplete.addOnce( function(){ RXKKPILDQT.add(AGKVNAGGLB[AGKVNAGGLB.length-1].TNFAGGMKXD); QYYXUWQADX(TXLWIIINGQ); } );;
		twReparto.start();
		//YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.scale).to( {x:QDTCADQEEX,y:QDTCADQEEX}, IRXOKNWTLV, BSXWFYLCEW,true);
		FXGSEGRXKC.pop();
		//JQSOOBSDDS();
};


function YVIUGJDUUO(TXLWIIINGQ){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,3,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",3);
	var GHTWROCHVV=FIGQBSJQGA("R",3);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce( function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); NESJSTWXWP(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};


function NESJSTWXWP(TXLWIIINGQ){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,4,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",4);
	var GHTWROCHVV=FIGQBSJQGA("R",4);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce( function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); IABLTISPHU(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};


function IABLTISPHU(TXLWIIINGQ){
	CBCNHFGWLU.push(new TVYNYTCQYW(FXGSEGRXKC[FXGSEGRXKC.length-1].SGCSHJVERI,FXGSEGRXKC[FXGSEGRXKC.length-1].UUOPKETETA,FXGSEGRXKC[FXGSEGRXKC.length-1].HVCFEWNDRF,FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD,5,null,null,null,FXGSEGRXKC[FXGSEGRXKC.length-1].MQUGCIUQII));
	EABXADHEVT('WWYKUMYJBJ');
	//BDRJVGFWQH.add(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	
	var NOFEDXHMLS=WIEVLYANFM("R",5);
	var GHTWROCHVV=FIGQBSJQGA("R",5);
	
	//var s = YMHIHSNADE.add.tween(FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD);
	twReparto.timeline = [];
	twReparto.target=FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD
	
		twReparto.to( {x:NOFEDXHMLS
		,y:GHTWROCHVV,
		angle : FXGSEGRXKC[FXGSEGRXKC.length-1].TNFAGGMKXD.angle + 270
		}
		, IRXOKNWTLV, BSXWFYLCEW);
		twReparto.onComplete.addOnce( function(){ BDRJVGFWQH.add(CBCNHFGWLU[CBCNHFGWLU.length-1].TNFAGGMKXD); UTVYHFEAFY(TXLWIIINGQ); } );
		twReparto.start();
		FXGSEGRXKC.pop();
};

